[build]
  publish = "."  # Root adalah folder src/pages
  
[[redirects]]
  from = "/components/*"
  to = "/src/components/:splat"
  status = 200
  
[[redirects]]
  from = "/assets/*"
  to = "/src/assets/:splat"
  status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/src/pages/index.html"
  status = 200