[build]
  # Jika index.html ada di src/pages, jadikan itu root publish
  publish = "src/pages"
  # command = ""  # kosongkan jika tidak perlu build

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200